aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "dixon.siu@gmail.com"
            git config --global user.name "dixonsiu"
            echo "machine github.com login dixonsiu password $GITHUB_TOKEN" > ~/.netrc
            cd mydataasia && yarn install
            GIT_USER=dixonsiu ORGANIZATION_NAME=MyDataAsia PROJECT_NAME=MyDataAsia.github.io yarn run publish-gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master